[2025-11-01T03:05:57.398+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-11-01T03:05:57.412+0530] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_google_analytics_dag.daily_visits_data_extration scheduled__2025-10-29T06:00:00+00:00 [queued]>
[2025-11-01T03:05:57.424+0530] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_google_analytics_dag.daily_visits_data_extration scheduled__2025-10-29T06:00:00+00:00 [queued]>
[2025-11-01T03:05:57.424+0530] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-11-01T03:05:57.515+0530] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): daily_visits_data_extration> on 2025-10-29 06:00:00+00:00
[2025-11-01T03:05:57.524+0530] {standard_task_runner.py:72} INFO - Started process 107393 to run task
[2025-11-01T03:05:57.554+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_google_analytics_dag', 'daily_visits_data_extration', 'scheduled__2025-10-29T06:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_google_analytics_dag.py', '--cfg-path', '/tmp/tmpyufcm1ep']
[2025-11-01T03:05:57.564+0530] {standard_task_runner.py:105} INFO - Job 4: Subtask daily_visits_data_extration
[2025-11-01T03:05:57.782+0530] {task_command.py:467} INFO - Running <TaskInstance: etl_google_analytics_dag.daily_visits_data_extration scheduled__2025-10-29T06:00:00+00:00 [running]> on host Abhijit.
[2025-11-01T03:05:57.972+0530] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_google_analytics_dag' AIRFLOW_CTX_TASK_ID='daily_visits_data_extration' AIRFLOW_CTX_EXECUTION_DATE='2025-10-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-29T06:00:00+00:00'
[2025-11-01T03:05:57.977+0530] {taskinstance.py:731} INFO - ::endgroup::
[2025-11-01T03:05:58.053+0530] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/adminabhi/gitrepo/dish-second-course/dags/etl_google_analytics_dag.py", line 50, in wrapper_daily_visits_extraction
    fetch_daily_visits_by_date(start_date=start_date, end_date=end_date, limit=50)
  File "/home/adminabhi/gitrepo/dish-second-course/src/etl/data_extractor.py", line 131, in fetch_daily_visits_by_date
    start_date.date(), end_date.date())
AttributeError: 'str' object has no attribute 'date'
[2025-11-01T03:05:58.113+0530] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_google_analytics_dag, task_id=daily_visits_data_extration, run_id=scheduled__2025-10-29T06:00:00+00:00, execution_date=20251029T060000, start_date=20251031T213557, end_date=20251031T213558
[2025-11-01T03:05:58.173+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-11-01T03:05:58.174+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task daily_visits_data_extration ('str' object has no attribute 'date'; 107393)
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/adminabhi/gitrepo/dish-second-course/dags/etl_google_analytics_dag.py", line 50, in wrapper_daily_visits_extraction
    fetch_daily_visits_by_date(start_date=start_date, end_date=end_date, limit=50)
  File "/home/adminabhi/gitrepo/dish-second-course/src/etl/data_extractor.py", line 131, in fetch_daily_visits_by_date
    start_date.date(), end_date.date())
AttributeError: 'str' object has no attribute 'date'
[2025-11-01T03:05:58.332+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-11-01T03:05:58.352+0530] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-11-01T03:05:58.353+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-11-01T04:05:53.492+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-11-01T04:05:53.503+0530] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_google_analytics_dag.daily_visits_data_extration scheduled__2025-10-29T06:00:00+00:00 [queued]>
[2025-11-01T04:05:53.509+0530] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_google_analytics_dag.daily_visits_data_extration scheduled__2025-10-29T06:00:00+00:00 [queued]>
[2025-11-01T04:05:53.509+0530] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-11-01T04:05:53.535+0530] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): daily_visits_data_extration> on 2025-10-29 06:00:00+00:00
[2025-11-01T04:05:53.538+0530] {standard_task_runner.py:72} INFO - Started process 144452 to run task
[2025-11-01T04:05:53.541+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_google_analytics_dag', 'daily_visits_data_extration', 'scheduled__2025-10-29T06:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/etl_google_analytics_dag.py', '--cfg-path', '/tmp/tmpkl8bwmnq']
[2025-11-01T04:05:53.543+0530] {standard_task_runner.py:105} INFO - Job 15: Subtask daily_visits_data_extration
[2025-11-01T04:05:53.591+0530] {task_command.py:467} INFO - Running <TaskInstance: etl_google_analytics_dag.daily_visits_data_extration scheduled__2025-10-29T06:00:00+00:00 [running]> on host Abhijit.
[2025-11-01T04:05:53.673+0530] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_google_analytics_dag' AIRFLOW_CTX_TASK_ID='daily_visits_data_extration' AIRFLOW_CTX_EXECUTION_DATE='2025-10-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-29T06:00:00+00:00'
[2025-11-01T04:05:53.674+0530] {taskinstance.py:731} INFO - ::endgroup::
[2025-11-01T04:05:53.691+0530] {data_extractor.py:130} INFO - Starting Daily Visits extraction from 2025-10-22 to 2025-10-28
[2025-11-01T04:05:53.692+0530] {data_extractor.py:136} INFO - Fetching Daily Visits for date 2025-10-22...
[2025-11-01T04:05:53.692+0530] {data_extractor.py:85} INFO - Fetching page 1 with params: {'start_date': '2025-10-22', 'end_date': '2025-10-22'}
[2025-11-01T04:05:56.067+0530] {api_client.py:38} ERROR - HTTP error 500: {"description":"Internal server error","error":500}

[2025-11-01T04:05:56.067+0530] {data_extractor.py:89} WARNING - No data returned for page 1.
[2025-11-01T04:05:56.067+0530] {data_extractor.py:150} WARNING - No Daily Visit data found for 2025-10-22.
[2025-11-01T04:05:56.067+0530] {data_extractor.py:136} INFO - Fetching Daily Visits for date 2025-10-23...
[2025-11-01T04:05:56.067+0530] {data_extractor.py:85} INFO - Fetching page 1 with params: {'start_date': '2025-10-23', 'end_date': '2025-10-23'}
[2025-11-01T04:05:58.315+0530] {api_client.py:38} ERROR - HTTP error 500: {"description":"Internal server error","error":500}

[2025-11-01T04:05:58.315+0530] {data_extractor.py:89} WARNING - No data returned for page 1.
[2025-11-01T04:05:58.315+0530] {data_extractor.py:150} WARNING - No Daily Visit data found for 2025-10-23.
[2025-11-01T04:05:58.316+0530] {data_extractor.py:136} INFO - Fetching Daily Visits for date 2025-10-24...
[2025-11-01T04:05:58.316+0530] {data_extractor.py:85} INFO - Fetching page 1 with params: {'start_date': '2025-10-24', 'end_date': '2025-10-24'}
[2025-11-01T04:06:00.564+0530] {api_client.py:38} ERROR - HTTP error 500: {"description":"Internal server error","error":500}

[2025-11-01T04:06:00.564+0530] {data_extractor.py:89} WARNING - No data returned for page 1.
[2025-11-01T04:06:00.564+0530] {data_extractor.py:150} WARNING - No Daily Visit data found for 2025-10-24.
[2025-11-01T04:06:00.564+0530] {data_extractor.py:136} INFO - Fetching Daily Visits for date 2025-10-25...
[2025-11-01T04:06:00.564+0530] {data_extractor.py:85} INFO - Fetching page 1 with params: {'start_date': '2025-10-25', 'end_date': '2025-10-25'}
[2025-11-01T04:06:02.930+0530] {api_client.py:38} ERROR - HTTP error 500: {"description":"Internal server error","error":500}

[2025-11-01T04:06:02.930+0530] {data_extractor.py:89} WARNING - No data returned for page 1.
[2025-11-01T04:06:02.930+0530] {data_extractor.py:150} WARNING - No Daily Visit data found for 2025-10-25.
[2025-11-01T04:06:02.930+0530] {data_extractor.py:136} INFO - Fetching Daily Visits for date 2025-10-26...
[2025-11-01T04:06:02.930+0530] {data_extractor.py:85} INFO - Fetching page 1 with params: {'start_date': '2025-10-26', 'end_date': '2025-10-26'}
[2025-11-01T04:06:05.038+0530] {api_client.py:38} ERROR - HTTP error 500: {"description":"Internal server error","error":500}

[2025-11-01T04:06:05.039+0530] {data_extractor.py:89} WARNING - No data returned for page 1.
[2025-11-01T04:06:05.039+0530] {data_extractor.py:150} WARNING - No Daily Visit data found for 2025-10-26.
[2025-11-01T04:06:05.039+0530] {data_extractor.py:136} INFO - Fetching Daily Visits for date 2025-10-27...
[2025-11-01T04:06:05.039+0530] {data_extractor.py:85} INFO - Fetching page 1 with params: {'start_date': '2025-10-27', 'end_date': '2025-10-27'}
[2025-11-01T04:06:07.234+0530] {api_client.py:38} ERROR - HTTP error 500: {"description":"Internal server error","error":500}

[2025-11-01T04:06:07.235+0530] {data_extractor.py:89} WARNING - No data returned for page 1.
[2025-11-01T04:06:07.235+0530] {data_extractor.py:150} WARNING - No Daily Visit data found for 2025-10-27.
[2025-11-01T04:06:07.235+0530] {data_extractor.py:157} INFO - ✅ Completed Daily Visits extraction for all dates.
[2025-11-01T04:06:07.235+0530] {python.py:240} INFO - Done. Returned value was: None
[2025-11-01T04:06:07.239+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-11-01T04:06:07.240+0530] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_google_analytics_dag, task_id=daily_visits_data_extration, run_id=scheduled__2025-10-29T06:00:00+00:00, execution_date=20251029T060000, start_date=20251031T223553, end_date=20251031T223607
[2025-11-01T04:06:07.302+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-11-01T04:06:07.317+0530] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-11-01T04:06:07.332+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
