[2025-11-01T03:19:17.164+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-11-01T03:19:17.180+0530] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_google_analytics_dag.daily_visits_bq_ingestion scheduled__2025-10-29T06:00:00+00:00 [queued]>
[2025-11-01T03:19:17.192+0530] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_google_analytics_dag.daily_visits_bq_ingestion scheduled__2025-10-29T06:00:00+00:00 [queued]>
[2025-11-01T03:19:17.193+0530] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-11-01T03:19:17.223+0530] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): daily_visits_bq_ingestion> on 2025-10-29 06:00:00+00:00
[2025-11-01T03:19:17.226+0530] {standard_task_runner.py:72} INFO - Started process 113512 to run task
[2025-11-01T03:19:17.232+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_google_analytics_dag', 'daily_visits_bq_ingestion', 'scheduled__2025-10-29T06:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/etl_google_analytics_dag.py', '--cfg-path', '/tmp/tmprz_1b7df']
[2025-11-01T03:19:17.235+0530] {standard_task_runner.py:105} INFO - Job 8: Subtask daily_visits_bq_ingestion
[2025-11-01T03:19:17.305+0530] {task_command.py:467} INFO - Running <TaskInstance: etl_google_analytics_dag.daily_visits_bq_ingestion scheduled__2025-10-29T06:00:00+00:00 [running]> on host Abhijit.
[2025-11-01T03:19:17.410+0530] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_google_analytics_dag' AIRFLOW_CTX_TASK_ID='daily_visits_bq_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-10-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-29T06:00:00+00:00'
[2025-11-01T03:19:17.411+0530] {taskinstance.py:731} INFO - ::endgroup::
[2025-11-01T03:19:29.386+0530] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/adminabhi/gitrepo/dish-second-course/dags/etl_google_analytics_dag.py", line 54, in wrapper_daily_visits_ingestion
    process_directory_by_date_range(start_date=start_date, end_date=end_date, project_id="dish-second-course", table_id="dish-second-course.analytics.daily_visits", base_path="data/daily_visits/")
  File "/home/adminabhi/gitrepo/dish-second-course/src/etl/bq_data_load.py", line 132, in process_directory_by_date_range
    bq_client = bigquery.Client(project=project_id)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 261, in __init__
    super(Client, self).__init__(
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/google/cloud/client/__init__.py", line 339, in __init__
    Client.__init__(
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/google/cloud/client/__init__.py", line 196, in __init__
    credentials, _ = google.auth.default(scopes=scopes)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/google/auth/_default.py", line 739, in default
    raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
google.auth.exceptions.DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-11-01T03:19:29.451+0530] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_google_analytics_dag, task_id=daily_visits_bq_ingestion, run_id=scheduled__2025-10-29T06:00:00+00:00, execution_date=20251029T060000, start_date=20251031T214917, end_date=20251031T214929
[2025-11-01T03:19:29.529+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-11-01T03:19:29.530+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task daily_visits_bq_ingestion (Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.; 113512)
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/adminabhi/gitrepo/dish-second-course/dags/etl_google_analytics_dag.py", line 54, in wrapper_daily_visits_ingestion
    process_directory_by_date_range(start_date=start_date, end_date=end_date, project_id="dish-second-course", table_id="dish-second-course.analytics.daily_visits", base_path="data/daily_visits/")
  File "/home/adminabhi/gitrepo/dish-second-course/src/etl/bq_data_load.py", line 132, in process_directory_by_date_range
    bq_client = bigquery.Client(project=project_id)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 261, in __init__
    super(Client, self).__init__(
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/google/cloud/client/__init__.py", line 339, in __init__
    Client.__init__(
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/google/cloud/client/__init__.py", line 196, in __init__
    credentials, _ = google.auth.default(scopes=scopes)
  File "/root/.cache/pypoetry/virtualenvs/dish-second-course-SaEmTrMc-py3.10/lib/python3.10/site-packages/google/auth/_default.py", line 739, in default
    raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
google.auth.exceptions.DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-11-01T03:19:29.622+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-11-01T03:19:29.644+0530] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-11-01T03:19:29.645+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-11-01T04:11:26.747+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-11-01T04:11:26.759+0530] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_google_analytics_dag.daily_visits_bq_ingestion scheduled__2025-10-29T06:00:00+00:00 [queued]>
[2025-11-01T04:11:26.766+0530] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_google_analytics_dag.daily_visits_bq_ingestion scheduled__2025-10-29T06:00:00+00:00 [queued]>
[2025-11-01T04:11:26.766+0530] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-11-01T04:11:26.794+0530] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): daily_visits_bq_ingestion> on 2025-10-29 06:00:00+00:00
[2025-11-01T04:11:26.797+0530] {standard_task_runner.py:72} INFO - Started process 148623 to run task
[2025-11-01T04:11:26.802+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_google_analytics_dag', 'daily_visits_bq_ingestion', 'scheduled__2025-10-29T06:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/etl_google_analytics_dag.py', '--cfg-path', '/tmp/tmpgwqd7tmv']
[2025-11-01T04:11:26.803+0530] {standard_task_runner.py:105} INFO - Job 20: Subtask daily_visits_bq_ingestion
[2025-11-01T04:11:26.854+0530] {task_command.py:467} INFO - Running <TaskInstance: etl_google_analytics_dag.daily_visits_bq_ingestion scheduled__2025-10-29T06:00:00+00:00 [running]> on host Abhijit.
[2025-11-01T04:11:26.947+0530] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_google_analytics_dag' AIRFLOW_CTX_TASK_ID='daily_visits_bq_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-10-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-29T06:00:00+00:00'
[2025-11-01T04:11:26.950+0530] {taskinstance.py:731} INFO - ::endgroup::
[2025-11-01T04:11:27.026+0530] {bq_data_load.py:168} INFO - ⏭️ No directories found for date 2025-10-22
[2025-11-01T04:11:27.026+0530] {bq_data_load.py:168} INFO - ⏭️ No directories found for date 2025-10-23
[2025-11-01T04:11:27.026+0530] {bq_data_load.py:168} INFO - ⏭️ No directories found for date 2025-10-24
[2025-11-01T04:11:27.026+0530] {bq_data_load.py:168} INFO - ⏭️ No directories found for date 2025-10-25
[2025-11-01T04:11:27.027+0530] {bq_data_load.py:168} INFO - ⏭️ No directories found for date 2025-10-26
[2025-11-01T04:11:27.027+0530] {bq_data_load.py:168} INFO - ⏭️ No directories found for date 2025-10-27
[2025-11-01T04:11:27.027+0530] {bq_data_load.py:168} INFO - ⏭️ No directories found for date 2025-10-28
[2025-11-01T04:11:27.027+0530] {python.py:240} INFO - Done. Returned value was: None
[2025-11-01T04:11:27.033+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-11-01T04:11:27.034+0530] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_google_analytics_dag, task_id=daily_visits_bq_ingestion, run_id=scheduled__2025-10-29T06:00:00+00:00, execution_date=20251029T060000, start_date=20251031T224126, end_date=20251031T224127
[2025-11-01T04:11:27.098+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-11-01T04:11:27.118+0530] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-11-01T04:11:27.134+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
